name: es.genshin-impact

on: 
  workflow_dispatch:
    inputs:
      consumer:
        description: 'Consumer name'
        required: true
        type: choice
        options:
        - prefixes
        - rarities

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      FANDOM_PASSWORD: ${{ secrets.FANDOM_PASSWORD }}
      FANDOM_USERNAME: ${{ secrets.FANDOM_USERNAME }}

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm i -g yarn

    - run: yarn install

    - run: yarn build:all

    - run: yarn genshin node dist/main.js ${{ github.event.inputs.consumer }}
